export const ADD_USER = 'ADD_USER';

export const AUTH = 'AUTH';
export const UNAUTH = 'UNAUTH';
export const CHECK_AUTH = 'CHECK_AUTH';

export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const UNAUTH_REQUESTED = 'UNAUTH_REQUESTED';
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const CHECK_AUTH_REQUESTED = 'CHECK_AUTH_REQUESTED';
